module.exports=[
      {
          digit:'0',
          lcdDigit:['._.','|.|','|_|']
      },
      {
          digit:'1',
          lcdDigit:['..|','..|','..|']
      },
      {
          digit:'2',
          lcdDigit:['._.','._|','|_.']
      },
      {
          digit:'3',
          lcdDigit:['._.','._|','._|']
      },
      {
          digit:'4',
          lcdDigit:['...','|_|','..|']
      },
      {
          digit:'5',
          lcdDigit:['._.','|_.','._|']
      },
      {
          digit:'6',
          lcdDigit:['._.','|_.','|_|']
      },
      {
          digit:'7',
          lcdDigit:['._.','..|','..|']
      },
      {
          digit:'8',
          lcdDigit:['._.','|_|','|_|']
      },
      {
          digit:'9',
          lcdDigit:['._.','|_|','._|']
      }
  ];
